# Generated by Django 5.1.2 on 2024-10-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='social_link',
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
