# Generated by Django 5.1.2 on 2024-10-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_social_link_customuser_github_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
