# Generated by Django 5.1.2 on 2024-11-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
