name: Django Docker Actions

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Build Docker Compose services
      run: docker compose -f docker-compose.yml up -d --build

    - name: Wait for services to be ready
      run: sleep 15


    - name: Run Django tests
      run: docker compose exec web python manage.py test


    - name: Down Docker Compose services
      if: always()
      run: docker compose down